catalog/accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView
from django.contrib.auth import views as auth_views
from rest_framework.routers import DefaultRouter


from .views import (
    register,
    login_view,
    logout_user,
    profile,
    edit_profile_view,
    confirm_email,
)
from ._views import AccountViewSet


app_name = "accounts"

router = DefaultRouter()
router.register(prefix=r"accounts", viewset=AccountViewSet, basename="accounts")


urlpatterns = [
    path("register/", register, name="register"),
    path("login/", login_view, name="login"),
    path("logout/", logout_user, name="logout_user"),
    path("profile/", profile, name="profile"),
    path("edit_profile/", edit_profile_view, name="edit_profile"),
    path(
        "password_change/",
        PasswordChangeView.as_view(
            success_url=reverse_lazy("accounts:password_change_done"),
            template_name="password_change.html",
        ),
        name="password_change",
    ),
    path(
        "password_change_done",
        PasswordChangeDoneView.as_view(template_name="password_change_done.html"),
        name="password_change_done",
    ),
    path("confirm_email/", confirm_email, name="confirm_email"),
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="password_reset/form.html",
            email_template_name="password_reset/email.html",
            success_url="done/",
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="password_reset/done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="password_reset/confirm.html",
            success_url=reverse_lazy("accounts:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="password_reset/complete.html"
        ),
        name="password_reset_complete",
    ),
]

urlpatterns += router.urls

catalog/catalog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework_simplejwt.views import TokenObtainPairView,TokenRefreshView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("products.urls", namespace="products")),
    path("", include("accounts.urls", namespace="accounts")),
    path("captcha/", include("captcha.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
        path(
            "api/docs/",
            SpectacularSwaggerView.as_view(url_name="schema"),
            name="swagger-ui",
        ),   
        path(
            "api/token", TokenObtainPairView.as_view(), name='token_obtain_pair'
        ),
        path(
            'api/token/refresh', TokenRefreshView.as_view(), name = 'refresh_token'
        )
        # path('api/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
    ]

catalog/products/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter

from products.views.views import index, about, product_details, cart_add, cart_detail, checkout
from products.views.product import ProductViewSet
from products.views.category import CategoryViewSet

app_name = "products"
router = DefaultRouter()
router.register(r"products", viewset=ProductViewSet)
router.register(r"category", viewset=CategoryViewSet)


urlpatterns = [
    path('', index, name='index'),
    path('about/', about, name='about'),
    path("product/<int:product_id>/", product_details, name="product_details"),
    path("cart_add/<int:product_id>/", cart_add, name="cart_add"),
    path("cart_details/<int:product_id>/", cart_detail, name="cart_details"),
    path("checkout/", checkout, name="checkout"),
]


urlpatterns += router.urls

catalog/products/forms.py
from django import forms
from .models import Order

class OrderCreateForm(forms.ModelForm):
    payment_method = forms.ChoiceField(choices={"liqpay":"With LiqPay", "monopay":"With MonoPay", "googlepay":"With Google Pay", "cash":"With Cash"})
    class Meta:
        model = Order
        fields = ['contact_name', 'contact_email', 'contact_phone', 'address', 'payment_method']
        labels = {'contact_name': 'Your Name:', 
                'contact_email': 'Your email address:', 
                'contact_phone': 'Your phone number:', 
                'address': 'Your address:',
                'payment_method': 'Payment Method:',
                }

catalog/products/views/category.py
from rest_framework.viewsets import ReadOnlyModelViewSet, ModelViewSet
from ..models import Category
from ..serializers import CategorySerializer

class CategoryViewSet(ModelViewSet):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer

catalog/products/views/product.py
from rest_framework.viewsets import ModelViewSet
from django_filters.rest_framework import DjangoFilterBackend
from rest_framework.filters import OrderingFilter
from rest_framework.permissions import IsAdminUser, AllowAny

from products.models import Product
from products.serializers.product_serializer import ProductSerializer
from ..filters import ProductFilter


class ProductViewSet(ModelViewSet):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    filter_backends = [DjangoFilterBackend, OrderingFilter]
    filterset_class = ProductFilter
    search_fields = ["name", "description"]
    ordering_fields = ["price", "rating"]

    def get_permissions(self):
        if self.action in ["create", "update", "partial_update", "destroy"]:
            return [IsAdminUser()]
        else:
            return [AllowAny()]

catalog/products/views/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import F, ExpressionWrapper, FloatField
from django.conf import settings
from django.contrib import messages
from rest_framework import viewsets, filters

from products.models import Product, Category, Cart, CartItem, Order, OrderItem, Payment
from ..forms import OrderCreateForm
from utils.email import send_order_confirmation_email

def calculate_discount(value, arg):
    return round((value * arg / 100), 2)

def index(request):
    products = Product.objects.all()
    categories = Category.objects.all()
    
    category_name = request.GET.get("category")
    filter_name = request.GET.get("filter")
    product_name = request.GET.get("search")
    min_price = request.GET.get("min_price")
    max_price = request.GET.get("max_price")
    
    product_amount = Product.objects.all().count()
    
    if category_name:
        products = products.filter(category=get_object_or_404(Category, name=category_name))
        product_amount = products.count()
        
    if product_name:
        products = products.filter(name__icontains=product_name)
        product_amount = products.count()
        
    if min_price:
        products = products.annotate(
        discount_price=ExpressionWrapper(
            F("price") * F("discount") / 100,
            output_field=FloatField(),
        )
    ).filter(discount_price__gte=min_price)
    product_amount = products.count()
        
    if max_price:
        products = products.annotate(
        discount_price=ExpressionWrapper(
            F("price") * F("discount") / 100,
            output_field=FloatField(),
        )
    ).filter(discount_price__lte=max_price)
    product_amount = products.count()
    
    match filter_name:
        case "price_increasing":
            products = products.order_by("price")
        case "price_decreasing":
            products = products.order_by("-price")
        case "rating":
            products = products.order_by("-rating")
        case "newest_first":
            products = products.order_by('-created_at')
        case "oldest_first":
            products = products.order_by('created_at')
            
    return render(request, 'index.html', context={"products":products, "categories":categories, "product_amount":product_amount})

def about(request):
    return render(request, 'about.html')

def product_details(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    return render(request, "product_details.html", {"product": product})

def cart_detail(request):
    if not request.user.is_authenticated:
        cart = request.session.get(settings.CART_SESSION_ID, dict())
        product_ids = cart.keys()
        products = Product.objects.filter(id__in = product_ids)
        cart_items = []
        total_price = 0
        for product in products:
            count = cart[str(product.id)]
            if count == 0:
                continue
            if product.discount:
                raw_price = calculate_discount(product.price, product.discount)
            else:
                raw_price = product.price
            price = count * raw_price
            total_price += price
            cart_items.append({"product" : product, "count" : count, "price": price})

    # else:
    #     try:
    #         cart = request.user.cart
    #     except Cart.DoesNotExist:
    #         cart = None
    #     if not cart or not cart.items.count():
    #         cart_items = []
    #         total_price = 0
    #     else:
    #         cart_items = cart.items.select_related("product").all()
    #         total_price = sum(item.product.price * item.amount  if not item.product.discount else round(((item.product.price * item.product.discount) / 100), 2) for item in cart_items)
    else:
        try:
            cart = request.user.cart
        except Cart.DoesNotExist:
            cart = None
        if not cart or not cart.items.count():
            cart_items = []
            total_price = 0
        else:
            raw_items = cart.items.select_related("product").all()
            cart_items = []
            total_price = 0
            for item in raw_items:
                product = item.product
                count = item.amount
                if count == 0:
                    continue
                if product.discount:
                    raw_price = calculate_discount(product.price, product.discount)
                else:
                    raw_price = product.price
                price = count * raw_price
                total_price += price
                cart_items.append({"product": product, "count": count, "price": price})
    return render(request, "cart_detail.html", context={"cart_items": cart_items, "total_price" : round(total_price,2)})

def cart_add(request, product_id:int):
    product = get_object_or_404(Product, id=product_id)
    if not request.user.is_authenticated:
        cart = request.session.get(settings.CART_SESSION_ID, {})
        product_key = str(product_id)
        if cart.get(product_key):
            cart[product_key] += 1
        else:
            cart[product_key] = 1
        request.session[settings.CART_SESSION_ID] = cart
    else:
        cart, _ = Cart.objects.get_or_create(user=request.user)
        cart_item, created = CartItem.objects.get_or_create(cart=cart, product=product)
        if not created:
            cart_item.amount += 1
            cart_item.save()
    return redirect('products:cart_detail')
    

def cart_delete(request, product_id:int):
    product = get_object_or_404(Product, id=product_id)
    product_key = str(product_id)
    if not request.user.is_authenticated:
        cart = request.session.get(settings.CART_SESSION_ID, {})
        cart[product_key] -= 1
        request.session[settings.CART_SESSION_ID] = cart
    else:
        cart, _ = Cart.objects.get_or_create(user=request.user)
        cart_item, created = CartItem.objects.get_or_create(cart=cart, product=product)
        if not created:
            cart_item.amount -= 1
            cart_item.save()
    return redirect("products:cart_detail")

def checkout(request):
    if (request.user.is_authenticated and not getattr(request.user, "cart", None)) or (
        not request.user.is_authenticated and not request.session.get(settings.CART_SESSION_ID)
        ):
        messages.error(request, 'Cart is emplty')
        return redirect('products:cart:detail')
    if request.method == "GET":
        form = OrderCreateForm()
        if request.user.is_authenticated:
            form.initial["contact_email"] = request.user.email
    elif request.method == "POST":
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            if request.user.is_authenticated:
                order.user = request.user
            order.save()
            
            if request.user.is_authenticated:
                cart = getattr(request.user, "cart")
                cart_items = cart.items.select_related("product")
            else:
                cart = request.session.get(settings.CART_SESSION_ID)
                cart_items = []
                for product_id, amount in cart.items():
                    product = Product.objects.get(id=product_id)
                    cart_items.append({"product":product, "amount":amount})
            items = OrderItem.objects.bulk_create(
                [
                    OrderItem(
                        order=order,
                        product=item.product,
                        amount=item.amount,
                        price=calculate_discount(
                            item.product.price, item.product.discount
                        ),
                    )
                    for item in cart_items
                ]
            )
            
            total_price = sum(item.product.price*item.amount for item in items)
            method = form.cleaned_data.get("payment_method")
            if method != "cash":
                Payment.objects.create(order=order, provider=method, amount=total_price)
            else:
                order.status = 2
            
            order.save()
            
            
            if request.user.is_authenticated:
                cart.items.all().delete()
            else:
                request.session[settings.CART_SESSION_ID] = {}
            send_order_confirmation_email(order=order)
            messages.success(request, 'Text')
            return redirect('products:index')
                


        
    return render(request, "checkout.html", context={"form":form})

catalog/products/templates/about.html
{% extends 'base.html' %}

{% block content %}
    <h1>About Us</h1>
    <p class="lead">Welcome to our page</p>
    <h2>Our Team:</h2>
    <ul>
        <li>
            Mavii
        </li>
    </ul>
{% endblock %}

catalog/products/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Products {% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css">
    <style>
        .register {
            align-self: flex-end;
            text-decoration: none;
            color: white;
            background-color:rgb(0, 101, 252);
            padding: 8px 15px;
            border-radius: 5px;
            transition: background-color 0.3s ease;
            font-weight: bold;
            display: inline-block;
            text-align: center;
        }
    </style>
</head>
<body class="d-flex flex-colums vh-100 ">
    <header>
        <nav class="navbar navber-dark bg-dark fixed-top">
            <div class="container d-flex flex-column">
                <div class="navbar-nav w-100 text-start">
                    <h4><a href="{% url 'products:index' %}" class="navbar-brand text-light">Home</a></h4>
                    {% if request.user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'accounts:profile' %}">{{ request.user.username }}</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout' %}">Log Out</a></li>
                    {% else %}
                        <li class="nav-item"><a href="{% url 'accounts:register' %}" class="navbar-brand text-light">Register</a></li>
                        <li class="nav-item"><a href="{% url 'accounts:login' %}" class="navbar-brand text-light">Login</a></li>
                    {% endif %}
                </div>
                <div class="nav-item text-light">
                    <form
                        action="{% url 'products:index' %}"
                        method="GET"
                        class="d-flex mx-auto">
                    <select name="category" class="form-select me-3" onchange="this.form.submit()"> 
                        <option value="" {% if not request.GET.category %} selected {% endif %}>Category</option>
                        {% for category in categories %}
                            <option value="{{ category.name }}" {% if request.GET.category == category.name %} selected {% endif %}>{{ category.name }}</option>
                        {% endfor %}
                    </select>
                    <select name="filter" id="form-select me-3" onchange="this.form.submit()" value="{{ request.GET.filter|default:'' }}">
                        <option value="price_increase" {% if request.GET.filter == 'price_increase' %} selected {% endif %}>Increasing price</option>
                        <option value="price_decrease" {% if request.GET.filter == 'price_decrease' %} selected {% endif %}>Decreasing price</option>
                        <option value="rating_increase" {% if request.GET.filter == 'rating_increase' %} selected {% endif %}>Increasing rating</option>
                        <option value="rating_decrease" {% if request.GET.filter == 'rating_decrease' %} selected {% endif %}>Decreasing rating</option>
                        
                    </select>
                    <input 
                    type="search" 
                    class="form-control me-3" 
                    name="search" 
                    placeholder="Product Search" 
                    onchange="this.form.submit()"
                    value="{{ request.GET.search|default:'' }}"
                    />

                    <label for="min_price">Minimum price:</label>
                    <input 
                    type="number" 
                    name="min_price"
                    class="w-25 form-control"
                    min="0"
                    onchange="this.form.submit()"
                    value="{{ request.GET.min_price|default:'' }}"
                    />

                    <label for="max_price">Maximum price:</label>
                    <input 
                    type="number" 
                    name="max_price"
                    class="w-25 form-control"
                    min="0"
                    onchange="this.form.submit()"
                    value="{{ request.GET.max_price|default:'' }}"
                    />

                    <label for="start_date">Start Date:</label>
                    <input type="datetime-local" name="start_date" class="form-control" value="{{ request.GET.start_date|default:'' }}" onchange="this.form.submit()">

                    <label for="end_date">End Date:</label>
                    <input type="datetime-local" name="end_date" class="form-control" value="{{ request.GET.end_date|default:'' }}" onchange="this.form.submit()">


                </form>                            
                </div>
                </div>
            </div>
        </nav>
    </header>

    <main class="container mt-5 flex-shrink-0" style="margin-top:200px;">
        {% block content %}
 

        {% endblock %}
    </main>

    <footer class="footer mt-5 py-3 px-2 bg-dark fixed-bottom">
        <a href="{% url 'products:about' %}">About Us</a>
    </footer>
    
</body>
</html>

catalog/products/templates/cart_details.html
{% block content %}
    <br><br><br>
    <br><br><br>
    <div class='container mt-4'>
        <h2>Your cart</h2>
        {% if cart_items %}

        <div class='table-responsive'>
            <table class='table table-bordered table-hover align-middle text-center'>
                <thead class='table-light'>
                    <tr>
                        <th>Product</th>
                        <th>Amount</th>
                        <th>Price</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in cart_items %}
                        <tr>
                            <td>{{ item.product.name }}</td>
                            <td>
                                <a href="{% url 'products:cart_remove' item.product.id %}" class="btn btn-danger">−</a>
                                {{ item.amount }}
                                <a href="{% url 'products:cart_add' item.product.id %}" class="btn btn-success">+</a>
                            </td>
                            <td>${{ item.product.price|floatformat:2 }}</td>
                            <td>
                                <a href="{% url 'products:cart_remove' item.product.id %}?remove_all=1" class="btn btn-danger">Remove</a>

                            </td>
                        </tr>
                    {% endfor %}
                    <tr class='table-secondary'>
                        <td class='text-start'>
                            <strong>Total: </strong>
                        </td>
                        <td class='text-end' colspan='4'>
                            <strong>
                                $ {{ total_price }}
                            </strong>
                        </td>
                    </tr>
                </tbody>
            </table>
            <a href="{% url 'checkout' %}" class = >Order checkout</a>
        </div>
        
        {% else %} 
            <div class='alert alert-info' role='alert'>
                Your cart is empty
            </div>
        {% endif %}
    </div>

{% endblock %}

catalog/products/templates/checkout.html
{% extends 'base.html' %}

{% block content %}
   <h2>Order chekout</h2>
   <form method= "POST">
        {% csrf_token %}
        {{form.as_p}}
        <button type= "button" value="Complete order" class= ""></input>

   </form>
{% endblock %}

catalog/products/templates/index.html
{% extends 'base.html' %}
{% load math_filters %}
{% block content %}
<div class="container mt-5">
    <h1 class="text-center">
        Catalog of products
    </h1>
    {% if length > 0 %}
        <h3 class="text-center">Products found: {{ length }}</h3>
    {% else %}
        <h3 class="text-center">No products found</h3> 
    {% endif %}
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for product in products %}
            <div class="col">
                <div class="card h-100 shadow-sm">
                    <img src="{{product.image_path|default:'https://www.collinsdictionary.com/images/full/apple_158989157.jpg'}}" 
                    alt="{{product.name}}" class="card-img-top"> 
                    <div class="card-body">
                        <h5 class="card-title">
                            {{ product.name }}
                        </h5>
                        {% if product.discount %}
                            <span class="text-success">
                                ${{ product.price|calculate_discount:product.discount }}
                            </span>
                            <span class="text-muted text-decoration-line-through">
                                ${{ product.price }}
                            </span>
                        {% else %}
                             <span class="text-success">
                                ${{ product.price }}
                             </span>   
                        {% endif %}
                        <div class="product-rating">
                            {% for i in "12345" %} 
                                {% if forloop.counter <= product.rating %}
                                    <i class="bi bi-star-fill text-warning"></i>
                                {% else %}
                                    <i class="bi bi-star text-muted"></i>
                                {% endif %} 
                            {% endfor %}
                        </div>
                        {% if not product.available %}
                            <small class="text-muted">
                                Not available
                            </small>
                        {% endif %}
                        <a href="{% url 'shop:product_details' product.id%}" class="btn btn-primary">More</a>
                    </div>
                </div>
            </div>
        {% endfor %}
</div>
{% endblock %}

catalog/products/templates/product_details.html
{% extends 'base.html' %} {% load math_filters %} {% block content %}
<br>
<br>
<div class="" container my-3>
  <div class="row">
    <div class="col-md-6">
      <img
        src="{{ product.image_path|default:'https://i.pinimg.com/736x/cd/27/54/cd2754f91a8592583c8d8ad0983bc400.jpg' }}"
        alt="product image"
        style="width: 600px; height: 700px; object-fit: cover; border-radius: 10px;"
      />
    </div>
    <div class="col-md-6">
      <h5>{{ product.name }}</h5>
      {% if product.description %}
      <p>Descripion: {{ product.description }}</p>
        
      {% endif %}
      <p>Category: {{ product.category.name }}</p>
      <div class="product-rating">
        {% for i in "12345" %} {% if forloop.counter <= product.rating %}
        <i class="bi bi-star-fill text-warning"></i>
        {% else %}
        <i class="bi bi-star text-muted"></i>
        {% endif %} {% endfor %}
      </div>
      {% if product.discount %}
      <span class="text-success">
        ${{ product.price|calculate_discount:product.discount}}
      </span>
      <span class="text-muted text-decoration-line-through">
        ${{product.price}}
      </span>

      {% else %}
      <span class="text-success"> ${{product.price}} </span>
      {% endif %}
    </div>
  </div>
    </div>
  </div>
</div>
{% endblock %}